# Add/remove 'LABEL_NAME' label if issue contains the word 'LABEL_TAG'
# LABEL_NAME:
#   - '(LABEL_TAG)'

ACCEPTANCE:
  - '(ACCEPTANCE)'
AGGREGATIONS:
  - '(AGGREGATIONS)'
BROKERS:
  - '(BROKER)'
BUG:
  - '(BUG)'
CODE RUB:
  - '(CODE RUB)'
CONTROLLERS:
  - '(CONTROLLER)'
DATA:
  - '(DATA)'
FOUNDATIONS:
  - '(FOUNDATION)'
INFRA:
  - '(INFRA)'
INTEGRATIONS:
  - '(INTEGRATION)'
ORCHESTRATIONS:
  - '(ORCHESTRATION)'
PROCESSINGS:
  - '(PROCESSING)'
PROVISION:
  - '(PROVISION)'
UNITS:
  - '(UNIT)'