# Add/remove 'LABEL_NAME' label if issue contains the word 'LABEL_TAG'
# LABEL_NAME:
#   - '(LABEL_TAG)'

ACCEPTANCE:
  - '(ACCEPTANCE: )'
AGGREGATIONS:
  - '(AGGREGATIONS: )'
BROKERS:
  - '(BROKERS: )'
BUG:
  - '(BUG: )'
CODE RUB:
  - '(CODE RUB: )'
CONTROLLERS:
  - '(CONTROLLERS: )'
DATA:
  - '(DATA: )'
FOUNDATIONS:
  - '(FOUNDATIONS: )'
INFRA:
  - '(INFRA: )'
INTEGRATIONS:
  - '(INTEGRATIONS: )'
ORCHESTRATIONS:
  - '(ORCHESTRATIONS: )'
PROCESSINGS:
  - '(PROCESSINGS: )'
PROVISION:
  - '(PROVISION: )'
UNITS:
  - '(UNITS: )'