# Add/remove 'LABEL_NAME' label if issue contains the word 'LABEL_TAG'
# LABEL_NAME:
#   - '(LABEL_TAG)'

UNITS:
  - '(UNIT)'
INTEGRATIONS:
  - '(INTEGRATION)'
ACCEPTANCE:
  - '(ACCEPTANCE)'
PROVISION:
  - '(PROVISION)'
ACCEPTANCE:
  - '(ACCEPTANCE)'
DATA:
  - '(DATA)'
INFRA:
  - '(INFRA)'
PROCESSINGS:
  - '(PROCESSING)'
ORCHESTRATIONS:
  - '(ORCHESTRATION)'
FOUNDATIONS:
  - '(FOUNDATION)'
CONTROLLERS:
  - '(CONTROLLER)'
CODE RUB:
  - '(CODE RUB)'
BROKERS:
  - '(BROKER)'
AGGREGATIONS:
  - '(AGGREGATIONS)'
BUG:
  - '(BUG)'