name: GottaGo Core Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out code
      uses: actions/checkout@v2

    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.5.22307.18
        include-prerelease: true
    
    - name: Restoring Packages
      run: dotnet restore
    
    - name: Building Projects
      run: dotnet build --no-restore
    
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal